### ISSUE TITLE
There is no .js entry code in published npm package.

### ISSUE THREAD

**Issue by jacobbubu** [zoomhub/node-deepzoomtools#13]
As the subject.

**Comment by aseemk** [comment]
Hmm, how do you mean? `package.json` defines `"main": "./lib"`, and the `lib` directory contains an `index._coffee` file (which gets compiled to `index.js` pre-publish).

And indeed, you can see it works here:

https://github.com/zoomhub/zoomhub/blob/a5fbec5cea75011dc409e49af9766f8a41f27a2d/lib/worker._coffee#L23

**Comment by gasi** [comment]
@jacobbubu I think @aseemk answered your question but please reopen if not :smile:
